// 此文件由 build.mjs 自动生成，请勿手改。数据源：list/<目录名>/game.json
window.GAMES = [
  { id: "1", img: "thumbs/1.webp", title: "维京战争", cat: "动作", entry: "index.html", hot: false },
  { id: "2", img: "thumbs/2.webp", title: "Space Huggers", cat: "动作", entry: "index.html", hot: true },
  { id: "3", img: "thumbs/3.webp", title: "报刊先生", cat: "休闲", entry: "index.html", hot: false },
  { id: "3d-bowling", img: "thumbs/3d-bowling.webp", title: "3D保龄球", cat: "体育", entry: "index.html", hot: false },
  { id: "4", img: "thumbs/4.webp", title: "植物大战僵尸", cat: "策略", entry: "index.htm", hot: true },
  { id: "5", img: "thumbs/5.webp", title: "3D魔方", cat: "益智", entry: "index.html", hot: false },
  { id: "6", img: "thumbs/6.webp", title: "青蛙吃苍蝇", cat: "休闲", entry: "index.html", hot: false },
  { id: "7", img: "thumbs/7.webp", title: "蜘蛛纸牌", cat: "棋牌", entry: "index.html", hot: true },
  { id: "8", img: "thumbs/8.webp", title: "贪吃蛇", cat: "休闲", entry: "index.html", hot: true },
  { id: "10", img: "thumbs/10.webp", title: "2048中文版", cat: "益智", entry: "index.html", hot: false },
  { id: "11", img: "thumbs/11.webp", title: "疯狂鲨鱼", cat: "动作", entry: "index.html", hot: false },
  { id: "12", img: "thumbs/12.webp", title: "飞机大战", cat: "射击", entry: "index.html", hot: true },
  { id: "14", img: "thumbs/14.webp", title: "贪吃蛇·极简版", cat: "休闲", entry: "index.html", hot: false },
  { id: "15", img: "thumbs/15.webp", title: "打鸭子", cat: "射击", entry: "index.html", hot: false },
  { id: "16", img: "thumbs/16.webp", title: "激流勇进", cat: "休闲", entry: "index.html", hot: false },
  { id: "21", img: "thumbs/21.webp", title: "星球防御", cat: "射击", entry: "index.html", hot: false },
  { id: "22", img: "thumbs/22.webp", title: "吃豆人", cat: "休闲", entry: "index.html", hot: true },
  { id: "25", img: "thumbs/25.webp", title: "2048", cat: "益智", entry: "index.html", hot: true },
  { id: "27", img: "thumbs/27.webp", title: "弹球打砖块", cat: "休闲", entry: "index.html", hot: false },
  { id: "30", img: "thumbs/30.webp", title: "射箭", cat: "体育", entry: "index.html", hot: false },
  { id: "31", img: "thumbs/31.webp", title: "飞机大战2.0", cat: "射击", entry: "index.html", hot: false },
  { id: "34", img: "thumbs/34.webp", title: "头像迷阵消除", cat: "益智", entry: "index.html", hot: false },
  { id: "35", img: "thumbs/35.webp", title: "变色弹球", cat: "休闲", entry: "index.html", hot: false },
  { id: "37", img: "thumbs/37.webp", title: "俄罗斯方块2.0", cat: "益智", entry: "index.html", hot: false },
  { id: "39", img: "thumbs/39.webp", title: "推箱子", cat: "益智", entry: "index.html", hot: true },
  { id: "42", img: "thumbs/42.webp", title: "极速赛车", cat: "体育", entry: "index.html", hot: false },
  { id: "43", img: "thumbs/43.webp", title: "大家来找茬", cat: "益智", entry: "index.html", hot: false },
  { id: "46", img: "thumbs/46.webp", title: "3D飞机躲避", cat: "射击", entry: "index.html", hot: false },
  { id: "47", img: "thumbs/47.webp", title: "兔子吃月饼", cat: "休闲", entry: "index.html", hot: false },
  { id: "50", img: "thumbs/50.webp", title: "疯狂打企鹅", cat: "动作", entry: "index.html", hot: false },
  { id: "52", img: "thumbs/52.webp", title: "双人坦克大战", cat: "射击", entry: "index.html", hot: true },
  { id: "55", img: "thumbs/55.webp", title: "飞行闯关", cat: "休闲", entry: "index.html", hot: false },
  { id: "56", img: "thumbs/56.webp", title: "3D熊出没", cat: "休闲", entry: "index.html", hot: false },
  { id: "57", img: "thumbs/57.webp", title: "3D拼图", cat: "益智", entry: "index.html", hot: false },
  { id: "60", img: "thumbs/60.webp", title: "2048军旗版", cat: "益智", entry: "index.html", hot: false },
  { id: "61", img: "thumbs/61.webp", title: "打地鼠", cat: "休闲", entry: "index.html", hot: true },
  { id: "62", img: "thumbs/62.webp", title: "驴子跳", cat: "休闲", entry: "index.html", hot: false },
  { id: "63", img: "thumbs/63.webp", title: "压扁小鸟", cat: "动作", entry: "index.htm", hot: false },
  { id: "64", img: "thumbs/64.webp", title: "像素小鸟", cat: "休闲", entry: "index.html", hot: true },
  { id: "66", img: "thumbs/66.webp", title: "经典飞机大战", cat: "射击", entry: "index.html", hot: false },
  { id: "67", img: "thumbs/67.webp", title: "简约打地鼠", cat: "休闲", entry: "index.html", hot: false },
  { id: "68", img: "thumbs/68.webp", title: "切积木", cat: "益智", entry: "index.html", hot: false },
  { id: "69", img: "thumbs/69.webp", title: "见缝插口红", cat: "休闲", entry: "index.html", hot: false },
  { id: "70", img: "thumbs/70.webp", title: "记忆翻牌", cat: "益智", entry: "index.html", hot: false },
  { id: "72", img: "thumbs/72.webp", title: "萝卜飞行记", cat: "休闲", entry: "index.html", hot: false },
  { id: "74", img: "thumbs/74.webp", title: "一笔连珠", cat: "益智", entry: "index.html", hot: false },
  { id: "75", img: "thumbs/75.webp", title: "森林协奏曲", cat: "休闲", entry: "index.html", hot: false },
  { id: "79", img: "thumbs/79.webp", title: "召唤神龙", cat: "休闲", entry: "index.html", hot: true },
  { id: "eight-ball", img: "thumbs/eight-ball.webp", title: "8 Ball Pool 桌球", cat: "休闲", entry: "index.html", hot: false },
];
